spring:
  application:
    name: News-letter

  cloud:
    function:
      definition: sendSubscribersInfo,processSubscribersInfo

    stream:
      function:
        definition: sendSubscribersInfo,processSubscribersInfo

      bindings:
       #producer bindings
        sendSubscribersInfo-out-0:
          destination: my-topic-new
          content-type: application/json

        #consumer bindings
        processSubscribersInfo-in-0:
          destination: my-topic-new
          group: newsletter-group
          content-type: application/json
      poller:
        fixed-delay: 5000

      kafka:
        binder:
          brokers: localhost:9092

