spring:
  application:
    name: News-letter

  cloud:
    function:
      definition: sendSubscribersInfo;processSubscribersInfo;sendSubscriberStatus

    stream:
      function:
        definition: sendSubscribersInfo,processSubscribersInfo

      bindings:

       #producer bindings
        sendSubscribersInfo-out-0:
          destination: my-topic-new
          content-type: application/json

       #producer bindings
        sendSubscriberStatus-out-0:
          destination: my-topic-new1
          content-type: text/plain

        #consumer bindings
        processSubscribersInfo-in-0:
          destination: my-topic-new
          group: newsletter-group
          content-type: application/json
      poller:
        fixed-delay: 5000

      kafka:
        binder:
          brokers: localhost:9092

